spring:
  application:
    name: primeiro-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    eduardo.estudo: debug

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20